CREATE TABLE TEST_minsun0714 (
    ID INT IDENTITY(1,1) CONSTRAINT PK_TEST_minsun0714 PRIMARY KEY,
    USER_NM NVARCHAR(100) NOT NULL,
    USER_ID NVARCHAR(50) NOT NULL,
    PW NVARCHAR(255) NOT NULL,
    REGI_USER NVARCHAR(50) NOT NULL,
    REGI_DT DATETIME DEFAULT GETDATE(),
	UPDA_USER NVARCHAR(50),
	UPDA_DT DATETIME,
    USE_YN CHAR(1) DEFAULT 'Y'
);

SELECT * FROM TEST_minsun0714;

INSERT INTO TEST_minsun0714 (USER_NM, USER_ID, PW, REGI_USER, REGI_DT)
VALUES ('관리자', 'ADMIN', 1234, 'ADMIN', GETDATE());

DROP TABLE TEST_minsun0714;

SELECT name FROM sys.databases;

EXEC xp_readerrorlog 0, 1, N'Server is listening on'

ALTER LOGIN minsun ENABLE;
SELECT name, type_desc, is_disabled FROM sys.sql_logins;
ALTER LOGIN minsun WITH PASSWORD = 'initial';


