CREATE TABLE EXER_QUERY_FIRST (
	FIRST_DIV VARCHAR(10),
	SECOND_DIV VARCHAR(10),
	THIRD_DIV VARCHAR(10),
	AMOUNT INT,
	CONSTRAINT pk PRIMARY KEY (FIRST_DIV, SECOND_DIV, THIRD_DIV)
);

SELECT * FROM EXER_QUERY_FIRST;

INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류01', N'소분류01', 45);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류01', N'소분류02', 62);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류01', N'소분류03', 35);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류02', N'소분류01', 66);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류02', N'소분류02', 82);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류02', N'소분류03', 43);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류03', N'소분류01', 63);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류03', N'소분류02', 16);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류01', N'중분류03', N'소분류03', 97);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류01', N'소분류01', 70);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류01', N'소분류02', 41);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류01', N'소분류03', 63);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류02', N'소분류01', 25);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류02', N'소분류02', 90);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류02', N'소분류03', 28);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류03', N'소분류01', 82);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류03', N'소분류02', 22);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류02', N'중분류03', N'소분류03', 34);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류01', N'소분류01', 57);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류01', N'소분류02', 89);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류01', N'소분류03', 7);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류02', N'소분류01', 66);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류02', N'소분류02', 48);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류02', N'소분류03', 31);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류03', N'소분류01', 59);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류03', N'소분류02', 39);
INSERT INTO test.dbo.EXER_QUERY_FIRST
(FIRST_DIV, SECOND_DIV, THIRD_DIV, AMOUNT)
VALUES(N'대분류03', N'중분류03', N'소분류03', 88);


SELECT FIRST_DIV, SECOND_DIV, sum(AMOUNT) AS 'SUM' FROM EXER_QUERY_FIRST GROUP BY FIRST_DIV, SECOND_DIV;

SELECT a.FIRST_DIV, a.FIRST_DIV_SUM, e.SECOND_DIV, e.THIRD_DIV, e.AMOUNT FROM EXER_QUERY_FIRST AS e
	INNER JOIN
	(SELECT FIRST_DIV, sum(AMOUNT) AS FIRST_DIV_SUM FROM EXER_QUERY_FIRST GROUP BY FIRST_DIV) as a
	ON a.FIRST_DIV = e.FIRST_DIV;


USE test
SELECT b.FIRST_DIV, b.FIRST_DIV_SUM, b.SECOND_DIV, c.SECOND_DIV_SUM, b.THIRD_DIV, b.AMOUNT AS THIRD_DIV_SUM FROM
	(SELECT a.FIRST_DIV, a.FIRST_DIV_SUM, e.SECOND_DIV, e.THIRD_DIV, e.AMOUNT FROM EXER_QUERY_FIRST AS e
	INNER JOIN
	(SELECT FIRST_DIV, sum(AMOUNT) AS FIRST_DIV_SUM FROM EXER_QUERY_FIRST GROUP BY FIRST_DIV) as a
	ON a.FIRST_DIV = e.FIRST_DIV) as b
	INNER JOIN
	(SELECT FIRST_DIV, SECOND_DIV, sum(AMOUNT) AS SECOND_DIV_SUM FROM EXER_QUERY_FIRST GROUP BY FIRST_DIV, SECOND_DIV) as c
	ON b.FIRST_DIV = c.FIRST_DIV AND b.SECOND_DIV = c.SECOND_DIV
	ORDER BY FIRST_DIV_SUM DESC, SECOND_DIV_SUM DESC, THIRD_DIV_SUM DESC;